# nixpacks.toml

# Set environment variables to minimize notifications
[variables]
    NPM_CONFIG_UPDATE_NOTIFIER = 'false'
    NPM_CONFIG_FUND = 'false'
    CADDY_VERSION = '2.7.5'

# Setup phase to add dependencies
[phases.setup]
    nixPkgs = ['...', 'jq']

# Extract Angular output path
[phases.output]
    dependsOn = ['setup']
    cmds = [
        'jq -r "[.projects[] | .architect.build.options.outputPath][0]" angular.json > angular_output_path'
    ]

# Caddy server setup
[phases.caddy]
    dependsOn = ['setup']
    cmds = [
        'curl -fsSLo caddy.tar.gz "https://github.com/caddyserver/caddy/releases/download/v${CADDY_VERSION}/caddy_${CADDY_VERSION}_linux_amd64.tar.gz"',
        'tar -zxvf caddy.tar.gz caddy',
        'chmod +x caddy'
    ]

# Format Caddyfile
[phases.fmt]
    dependsOn = ['caddy']
    cmds = ['caddy fmt --overwrite Caddyfile']

# Start the server
[start]
    cmd = 'export ANGULAR_OUTPUT_PATH=$(cat angular_output_path); ./caddy run --config Caddyfile --adapter caddyfile 2>&1'
